const theme = {
  colors: {
    grayscaleTitleActive: '#14142B',
    grayscaleBody: '#4E4B66',
    grayscaleLabel: '#6E7191',
    grayscalePlaceholder: '#A0A3BD',
    grayscaleLine: '#D9DBE9',
    grayscaleInputBackground: '#EFF0F6',
    grayscaleBackground: '#F7F7FC',
    grayscaleOffWhite: '#FCFCFC',
    primary: '#5F2EEA',
    primaryDark: '#2A00A2',
    primaryDarkmode: '#BCA4FF',
    primaryLight: '#E4DAFF',
    primaryBG: '#F3EFFF',
    secondary: '#1CC8EE',
    secondaryDark: '#0096B7',
    secondaryDarkmode: '#82E9FF',
    secondaryLight: '#F1FCFF',
    secondaryBG: '#DEF9FF',
    error: '#ED2E7E',
    errorDark: '#C30052',
    errorDarkmode: '#FF84B7',
    errorLight: '#FFF3F8',
    errorBG: '#FFDFED',
    success: '#00BA88',
    successDark: '#00966D',
    successDarkmode: '#34EAB9',
    successLight: '#F2FFFB',
    successBG: '#DFFFF6',
    warning: '#F4B740',
    warningDark: '#946200',
    warningDarkmode: '#FFD789',
    warningLight: '#FFF9EF',
    warningBG: '#FFF4DF',
  },
}

export default theme
